// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LibrarySystemServer.CompiledModels
{
    public partial class LibrarySystemContextModel
    {
        private LibrarySystemContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("60cdf8db-552b-4af7-b8dd-ce59e384ef04"), entityTypeCount: 11)
        {
        }

        partial void Initialize()
        {
            var book = BookEntityType.Create(this);
            var borrowRecord = BorrowRecordEntityType.Create(this);
            var member = MemberEntityType.Create(this);
            var refreshToken = RefreshTokenEntityType.Create(this);
            var revokedToken = RevokedTokenEntityType.Create(this);
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);

            BorrowRecordEntityType.CreateForeignKey1(borrowRecord, member);
            BorrowRecordEntityType.CreateForeignKey2(borrowRecord, book);
            BorrowRecordEntityType.CreateForeignKey3(borrowRecord, member);
            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, member);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, member);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, member);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, member);

            BookEntityType.CreateAnnotations(book);
            BorrowRecordEntityType.CreateAnnotations(borrowRecord);
            MemberEntityType.CreateAnnotations(member);
            RefreshTokenEntityType.CreateAnnotations(refreshToken);
            RevokedTokenEntityType.CreateAnnotations(revokedToken);
            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);

            AddAnnotation("ProductVersion", "9.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
