// <auto-generated />
using LibrarySystemServer.CompiledModels;
using LibrarySystemServer.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(LibrarySystemContext), typeof(LibrarySystemContextModel))]
